# Generated by Django 4.2.16 on 2024-12-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_alter_letter_options_alter_letter_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
